import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Header from "@/components/custom/Header";

const manRope = Manrope({ subsets: ["latin"], variable: "--font-manRope" });

export const metadata: Metadata = {
  title: "Pizza App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          manRope.variable
        )}
      >
       <Header/>
        <div className="main">{children}</div>
      </body>
    </html>
  );
}
